[[carousel_slides]]
caption = "EVAC+, ISMRM 2023"
description = ""
img = "https://raw.githubusercontent.com/dipy/dipy_data/master/dipy_main_evac.png"
link = "https://arxiv.org/abs/2206.02837"

[[carousel_slides]]
caption = "Patch2Self, NeurIPS 2020"
description = ""
img = "https://raw.githubusercontent.com/dipy/dipy_data/master/patch2self_banner.PNG"

[[carousel_slides]]
caption = "BUAN, Nature 2020"
description = ""
img = "https://raw.githubusercontent.com/dipy/dipy_data/master/buan_profiles.png"

[[carousel_slides]]
caption = "SLR, NeuroImage 2015"
description = ""
img = "https://github.com/Garyfallidis/garyfallidis.github.com/blob/master_bak/images/slr_banner.jpg?raw=true"

[[carousel_slides]]
caption = "Quick Bundles, Frontiers 2012"
description = ""
img = "https://github.com/Garyfallidis/garyfallidis.github.com/blob/master_bak/images/quickbundles_banner.jpg?raw=true"

[[explore_items]]
title = "Command-Line Interfaces"
icon = "cli.svg"
description = "All the algorithms are available using CLI. You can also create your own algorithms."
link = "https://dipy.org/documentation/1.7.0/interfaces/"

[[explore_items]]
title = "Statistical Analysis"
icon = "stat.svg"
description = "DIPY allows you to use different methods like BUAN, AFQ, K-Fold cross validation."
link = "https://dipy.org/documentation/1.7.0/interfaces/"

[[explore_items]]
title = "Reconstruction"
icon = "reconstruction.svg"
description = "<b>Single shell</b>: DTI, CSA, SFM, SDT, Q-Ball, CSD, and many more. <br/>  <b>Multi shell</b>: GQI, DTI, DKI, SHORE, MAPMRI, MSMT-CSD, and many more."
link = "https://dipy.org/documentation/1.7.0/interfaces/"

[[explore_items]]
title = "Registration"
icon = "registration.svg"
description = "Affine Registration, Diffeomorphic 2D/3D Registration, Streamlines based Registration, and much more."
link = "https://dipy.org/documentation/1.7.0/interfaces/"

[[explore_items]]
title = "Tractography"
icon = "tractography.svg"
description = "Probabilistic Tracking, Deterministic Tracking, PFT Tracking, and much more."
link = "https://dipy.org/documentation/1.7.0/interfaces/"

[[explore_items]]
title = "Denoising"
icon = "denoise.png"
description = "Affine Registration, Diffeomorphic 2D/3D Registration, Streamlines based Registration, and much more."
link = "https://dipy.org/documentation/1.7.0/interfaces/"

[[explore_items]]
title = "Visualization"
icon = "chart.png"
description = "ODFs visualization, interactive tractogram visualization, Advanced UI and Shaders, and much more."
link = "https://dipy.org/documentation/1.7.0/interfaces/"

[[explore_items]]
title = "Pre-Processing"
icon = "preprocessing.png"
description = "Brain extraction, SNR estimation, Reslice Datasets, and much more."
link = "https://dipy.org/documentation/1.7.0/interfaces/"

[[sponsors]]
name = "NIH NIBIB"
image = "NIH_NIBIB.png"
url = "https://www.nibib.nih.gov/"

[[sponsors]]
name = "Luddy IU"
image = "luddy.png"
url = "https://luddy.indiana.edu/"

[[sponsors]]
name = "Google Summer of Code"
image = "gsoc.png"
url = "https://summerofcode.withgoogle.com/"

[[sponsors]]
name = "Indiana Univesity"
image = "iu.webp"
url = "https://www.iu.edu/"

[[sponsors]]
name = "UW eScience Institute"
image = "uwescience.png"
url = "https://escience.washington.edu/"
