name: delete preview on PR close
on:
  pull_request:
    types: [closed]

jobs:
  delete_preview:
    runs-on: ubuntu-latest
    env:
      PR_PATH: pull/${{github.event.number}}
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Delete preview
        run: |
            git rm -r ${{ env.PR_PATH }}
            git commit -m "Delete preview for PR #${{ github.event.number }}"
            git push origin gh-pages

      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "🪓 PR closed, deleted preview at https://github.com/${{ github.repository }}/tree/gh-pages/${{ env.PR_PATH }}/"