name: github pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        PR_PATH: pull/${{github.event.number}}
    steps:
      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        if: github.ref != 'refs/heads/master'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "Starting deployment of preview ⏳..."

      - name: Checkout website repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt

      - name: Build website
        uses: ammaraskar/sphinx-action@master
        with:
            docs-folder: "."

      - name: Upload HTML
        uses: actions/upload-artifact@v1
        with:
            name: DocumentationHTML
            path: _build/html/
