name: Github Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        PR_PATH: dipy.org/pull/${{github.event.number}}
        BASE_URL: https://dipy.github.io/dipy.org
        HEAD: ${{ github.event.pull_request.head.repo.full_name }}
        BASE: ${{ github.repository }}
        NB: ${{github.event.number}}
        REF: ${{github.ref}}
        STATUS: ${{github.event.pull_request.head.repo.full_name != github.repository}}
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build website
        run: |
            make -C . html

      - name: Upload HTML
        uses: actions/upload-artifact@v1
        with:
            name: DocumentationHTML
            path: _build/html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event.pull_request.head.repo.full_name == '' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_build/html
            user_name: 'github-actions[bot]'
            user_email: 'github-actions[bot]@users.noreply.github.com'
            commit_message: ${{ github.event.head_commit.message }}
        #   cname: ${{ env.DOMAIN  # TODO: set this if you're using a custom domain.

      - name: Deploy to PR preview
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event.pull_request.head.repo.full_name != '' && github.event.pull_request.head.repo.full_name != github.repository }}
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          external_repository:  dipy/preview-html
          publish_dir: ./_build/html
          publish_branch: main
          destination_dir: ${{ env.PR_PATH }}
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}

